select * from order_items_refunds;
delete from order_items_refunds where order_item_id=1;
select * from order_items_refunds;
select * from thoughts;
delete from thoughts where payment_id=1;
select * from payments;
delete from payments where boss_payments=1;
select * from payments;
select * from manager_orders;
delete from manager_orders where order_id=1;
select * from manager_orders;
select * from orders;
select * from managers;
delete from managers where id=1;
delete from managers where id=2;
select * from orders;
delete from orders  where user_id=2;
select * from users;
delete from users where id=2;
delete from users where id=1;
select * from users;
select * from orders;