drop table if exists attendance cascade;
drop table if exists building cascade;
drop table if exists meeting cascade;
drop table if exists people cascade;
drop table if exists residence cascade;
drop table if exists room cascade;
drop table if exists room_reservation cascade;
drop table if exists thought cascade;
drop function if exists assign_room_to_meeting() cascade;